//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCategory()
        {
            this.tblProduct = new HashSet<tblProduct>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "Bu alan gerekli")]
        [DisplayName("Kategori Adý")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Bu alan gerekli")]
        [DisplayName("Kategori Açýklamasý")]
        public string Description { get; set; }
        [DisplayName("Kategori Resmi")]
        public string PictureLink { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProduct { get; set; }
    }
}
