//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblShoppingCart = new HashSet<tblShoppingCart>();
        }
        
        [DisplayName("Sipariþ Numarasý")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Sipariþ Adresini Giriniz")]
        [DisplayName("Sipariþ Adresi")]
        public int AdressId { get; set; }
        [DisplayName("Sipariþ Tarihi")]
        public System.DateTime Date { get; set; }
        [DisplayName("Sipariþ Onayý")]
        public Nullable<bool> isShipped { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShoppingCart> tblShoppingCart { get; set; }
        public virtual tblAddress tblAddress { get; set; }
    }
}
