//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblShoppingCart = new HashSet<tblShoppingCart>();
        }

        public int Id { get; set; }

        [DisplayName("Ürün Adý")]
        [Required(ErrorMessage = "Bu alan gerekli")]
        public string Name { get; set; }

        [DisplayName("Ürün Resmi")]
        public string PictureLink { get; set; }

        [AllowHtml]
        [UIHint("tinymce_full_compressed")]
        [DisplayName("Ürün Açýklamasý")]
        [Required(ErrorMessage = "Bu alan gerekli")]
        public string Description { get; set; }

        [DisplayName("Ürün Fiyatý")]
        [Required(ErrorMessage = "Bu alan gerekli")]
        public int Price { get; set; }

        [DisplayName("Stok Miktarý")]
        [Required(ErrorMessage = "Bu alan gerekli")]
        public int Stock { get; set; }

        [DisplayName("Kategori Adý")]
        [Required(ErrorMessage = "Bu alan gerekli")]
        public Nullable<int> CategoryId { get; set; }

        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShoppingCart> tblShoppingCart { get; set; }
    }
}
