//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tblShoppingCart
    {
        public int Id { get; set; }
        [DisplayName("Toplam Tutar")]
        public int TotalPrice { get; set; }
        [DisplayName("Miktar")]
        public int Amount { get; set; }
        [DisplayName("Kullanýcý ID")]
        public int UserId { get; set; }
        [DisplayName("Urun ID")]
        public int ProductId { get; set; }
        public Nullable<int> OrderId { get; set; }

        public virtual tblOrder tblOrder { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
